### PR TITLE
Working grunt

### PR DESCRIPTION
**Pull request by bdougie**
#1 

The project should work as soon as you clone it. The additions I saw, I removed. Grunt works as expected.

### CODE REVIEW

**Comment by bdougie** [comment]
Let me know if you have questions about this pull requests, or pull requests in general

**Comment by Chammz** [comment]
I believe I got the web server property (not sure if that is the right word?) from a stackoverflow article, but wasn't sure if that was necessary to run a web server using grunt. Was this what was causing the issue, or was it the first bit with the `registerTask` command?

**Comment by Chammz** [comment]
Also hopefully i did the pull request right. I merged the commit into the remote cp-4-templates from the github interface, then in terminal... `git pull checkpoint-4-templates`, `git checkout master`, `git commit` the change, `git push origin master`? Not sure if there is a faster way to do that?

**Comment by bdougie** [comment]
Your path for merging is fine, and probably the fastest. As far as Grunt, the file provided is all you need. Bloc will be removing Grunt eventually because it really isn't necessary and explanation of it was already removed from the curriculum. 

The first bit, was duplicating your default `grunt` command, which made it just do nothing. `hapi` which is included in the grunt file is a plugin to add a web server. Again we do not explain either which is why we will be removing it eventually.

https://hapijs.com/
http://gruntjs.com/

**Pull request merged**
